fields:
  - name: deploy
    type: radio-fieldset
    values:
      cc: Clean cluster with pre-deployed HelloWorld example
      cmd: Deploy custom helm or stack via shell command
    default: cc
    showIf:
      cmd:
        name: cmd
        type: text
        height: 65
        required: true
        hideLabel: true
        default: |-
          helm repo add ibm-charts https://raw.githubusercontent.com/IBM/charts/master/repo/stable/
          helm install --name default --set autoscaling.enabled=true --set autoscaling.minReplicas=2 --set resources.constraints.enabled=true --set resources.requests.cpu=400m --set resources.limits.cpu=700m ibm-charts/ibm-open-liberty --version 1.6.0  --debug
          kubectl apply -f https://raw.githubusercontent.com/jelastic-jps/kubernetes/v1.15.5/addons/ingress/openliberty.yaml
